//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextInverterClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TextInverterWebServiceSoap")]
    public interface TextInverterWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name inputstring from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TextInverter", ReplyAction="*")]
        TextInverterClient.ServiceReference1.TextInverterResponse TextInverter(TextInverterClient.ServiceReference1.TextInverterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TextInverter", ReplyAction="*")]
        System.Threading.Tasks.Task<TextInverterClient.ServiceReference1.TextInverterResponse> TextInverterAsync(TextInverterClient.ServiceReference1.TextInverterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TextInverterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TextInverter", Namespace="http://tempuri.org/", Order=0)]
        public TextInverterClient.ServiceReference1.TextInverterRequestBody Body;
        
        public TextInverterRequest() {
        }
        
        public TextInverterRequest(TextInverterClient.ServiceReference1.TextInverterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TextInverterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputstring;
        
        public TextInverterRequestBody() {
        }
        
        public TextInverterRequestBody(string inputstring) {
            this.inputstring = inputstring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TextInverterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TextInverterResponse", Namespace="http://tempuri.org/", Order=0)]
        public TextInverterClient.ServiceReference1.TextInverterResponseBody Body;
        
        public TextInverterResponse() {
        }
        
        public TextInverterResponse(TextInverterClient.ServiceReference1.TextInverterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TextInverterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TextInverterResult;
        
        public TextInverterResponseBody() {
        }
        
        public TextInverterResponseBody(string TextInverterResult) {
            this.TextInverterResult = TextInverterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TextInverterWebServiceSoapChannel : TextInverterClient.ServiceReference1.TextInverterWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextInverterWebServiceSoapClient : System.ServiceModel.ClientBase<TextInverterClient.ServiceReference1.TextInverterWebServiceSoap>, TextInverterClient.ServiceReference1.TextInverterWebServiceSoap {
        
        public TextInverterWebServiceSoapClient() {
        }
        
        public TextInverterWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextInverterWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextInverterWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextInverterWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextInverterClient.ServiceReference1.TextInverterResponse TextInverterClient.ServiceReference1.TextInverterWebServiceSoap.TextInverter(TextInverterClient.ServiceReference1.TextInverterRequest request) {
            return base.Channel.TextInverter(request);
        }
        
        public string TextInverter(string inputstring) {
            TextInverterClient.ServiceReference1.TextInverterRequest inValue = new TextInverterClient.ServiceReference1.TextInverterRequest();
            inValue.Body = new TextInverterClient.ServiceReference1.TextInverterRequestBody();
            inValue.Body.inputstring = inputstring;
            TextInverterClient.ServiceReference1.TextInverterResponse retVal = ((TextInverterClient.ServiceReference1.TextInverterWebServiceSoap)(this)).TextInverter(inValue);
            return retVal.Body.TextInverterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TextInverterClient.ServiceReference1.TextInverterResponse> TextInverterClient.ServiceReference1.TextInverterWebServiceSoap.TextInverterAsync(TextInverterClient.ServiceReference1.TextInverterRequest request) {
            return base.Channel.TextInverterAsync(request);
        }
        
        public System.Threading.Tasks.Task<TextInverterClient.ServiceReference1.TextInverterResponse> TextInverterAsync(string inputstring) {
            TextInverterClient.ServiceReference1.TextInverterRequest inValue = new TextInverterClient.ServiceReference1.TextInverterRequest();
            inValue.Body = new TextInverterClient.ServiceReference1.TextInverterRequestBody();
            inValue.Body.inputstring = inputstring;
            return ((TextInverterClient.ServiceReference1.TextInverterWebServiceSoap)(this)).TextInverterAsync(inValue);
        }
    }
}
